"""fresh-db-migrations

Revision ID: c7dbc495d092
Revises: 
Create Date: 2026-01-21 19:42:18.376976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c7dbc495d092'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop existing ENUM types if they exist (from previous migrations)
    # This ensures a clean slate for fresh database setup
    op.execute("DROP TYPE IF EXISTS businesstype CASCADE")
    op.execute("DROP TYPE IF EXISTS accounttype CASCADE")
    op.execute("DROP TYPE IF EXISTS plantype CASCADE")
    op.execute("DROP TYPE IF EXISTS subscriptionstatus CASCADE")
    
    op.create_table('businesses',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('business_type', sa.Enum('INDIVIDUAL', 'SERVICES', 'ECOMMERCE', name='businesstype'), nullable=True),
    sa.Column('business_subtype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('business_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_verification_expires_at', sa.DateTime(), nullable=True),
    sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('google_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_reset_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(), nullable=True),
    sa.Column('account_type', sa.Enum('free', 'premium', name='accounttype'), nullable=False),
    sa.Column('current_plan', sa.Enum('FREE', 'BASIC', 'CUSTOM', name='plantype'), nullable=False),
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deletion_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_deleted'), 'user', ['deleted'], unique=False)
    op.create_index(op.f('ix_user_google_id'), 'user', ['google_id'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_stripe_customer_id'), 'user', ['stripe_customer_id'], unique=False)
    op.create_table('websites',
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=True),
    sa.Column('subdomain', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('website_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('favicon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('last_published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('website_id')
    )
    op.create_index(op.f('ix_websites_business_id'), 'websites', ['business_id'], unique=False)
    op.create_index(op.f('ix_websites_subdomain'), 'websites', ['subdomain'], unique=True)
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_credits',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('plan_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('credits_balance', sa.Integer(), nullable=False),
    sa.Column('subscription_ends_at', sa.DateTime(), nullable=True),
    sa.Column('last_credit_grant_at', sa.DateTime(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('last_reset_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_table('business_users',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('business_id', 'user_id')
    )
    op.create_table('credit_transactions',
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('credits_change', sa.Integer(), nullable=False),
    sa.Column('credits_balance_after', sa.Integer(), nullable=False),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_credit_transactions_business_id'), 'credit_transactions', ['business_id'], unique=False)
    op.create_index(op.f('ix_credit_transactions_created_at'), 'credit_transactions', ['created_at'], unique=False)
    op.create_table('purchase',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_successful', sa.Boolean(), nullable=False),
    sa.Column('download_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_purchase_id'), 'purchase', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_user_id'), 'purchase', ['user_id'], unique=False)
    op.create_table('service_business_profiles',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('yelp_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('google_maps_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.business_id'], ),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIALING', 'CANCELED', 'EXPIRED', 'PAST_DUE', 'UNPAID', 'INCOMPLETE', 'INCOMPLETE_EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_id'), 'subscription', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_stripe_subscription_id'), 'subscription', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscription_user_id'), 'subscription', ['user_id'], unique=True)
    op.create_table('website_pages',
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('page_path', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('page_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('last_published_at', sa.DateTime(), nullable=True),
    sa.Column('last_s3_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_cloudfront_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_invalidation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('publish_count', sa.Integer(), nullable=False),
    sa.Column('last_edited_at', sa.DateTime(), nullable=True),
    sa.Column('current_generation_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('preview_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dev_task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['websites.website_id'], ),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_index(op.f('ix_website_pages_page_path'), 'website_pages', ['page_path'], unique=False)
    op.create_index(op.f('ix_website_pages_website_id'), 'website_pages', ['website_id'], unique=False)
    op.create_table('generation_versions',
    sa.Column('generation_version_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('generation_scope', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('workflow_run_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('query_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['website_pages.page_id'], ),
    sa.PrimaryKeyConstraint('generation_version_id')
    )
    op.create_index(op.f('ix_generation_versions_created_at'), 'generation_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_generation_versions_entity_id'), 'generation_versions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_generation_versions_status'), 'generation_versions', ['status'], unique=False)
    op.create_table('page_publish_history',
    sa.Column('publish_id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('s3_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cloudfront_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invalidation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('html_version_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('html_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['website_pages.page_id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['websites.website_id'], ),
    sa.PrimaryKeyConstraint('publish_id')
    )
    op.create_index(op.f('ix_page_publish_history_business_id'), 'page_publish_history', ['business_id'], unique=False)
    op.create_index(op.f('ix_page_publish_history_page_id'), 'page_publish_history', ['page_id'], unique=False)
    op.create_index(op.f('ix_page_publish_history_published_at'), 'page_publish_history', ['published_at'], unique=False)
    op.create_index(op.f('ix_page_publish_history_website_id'), 'page_publish_history', ['website_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_publish_history_website_id'), table_name='page_publish_history')
    op.drop_index(op.f('ix_page_publish_history_published_at'), table_name='page_publish_history')
    op.drop_index(op.f('ix_page_publish_history_page_id'), table_name='page_publish_history')
    op.drop_index(op.f('ix_page_publish_history_business_id'), table_name='page_publish_history')
    op.drop_table('page_publish_history')
    op.drop_index(op.f('ix_generation_versions_status'), table_name='generation_versions')
    op.drop_index(op.f('ix_generation_versions_entity_id'), table_name='generation_versions')
    op.drop_index(op.f('ix_generation_versions_created_at'), table_name='generation_versions')
    op.drop_table('generation_versions')
    op.drop_index(op.f('ix_website_pages_website_id'), table_name='website_pages')
    op.drop_index(op.f('ix_website_pages_page_path'), table_name='website_pages')
    op.drop_table('website_pages')
    op.drop_index(op.f('ix_subscription_user_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_stripe_subscription_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_id'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_table('service_business_profiles')
    op.drop_index(op.f('ix_purchase_user_id'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_id'), table_name='purchase')
    op.drop_table('purchase')
    op.drop_index(op.f('ix_credit_transactions_created_at'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_business_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_table('business_users')
    op.drop_table('business_credits')
    op.drop_table('article')
    op.drop_index(op.f('ix_websites_subdomain'), table_name='websites')
    op.drop_index(op.f('ix_websites_business_id'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_user_stripe_customer_id'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_google_id'), table_name='user')
    op.drop_index(op.f('ix_user_deleted'), table_name='user')
    op.drop_table('user')
    op.drop_table('businesses')
    
    # Drop ENUM types
    op.execute("DROP TYPE IF EXISTS businesstype CASCADE")
    op.execute("DROP TYPE IF EXISTS accounttype CASCADE")
    op.execute("DROP TYPE IF EXISTS plantype CASCADE")
    op.execute("DROP TYPE IF EXISTS subscriptionstatus CASCADE")
    # ### end Alembic commands ###
